services:

  db_log:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: tp_log
      MYSQL_USER: log_user
      MYSQL_PASSWORD: log_pass
    ports:
      - "3309:3306"
    volumes:
      - db_log_data:/var/lib/mysql
      - ./sql_log:/docker-entrypoint-initdb.d:ro

  log_service:
    build: ./log_service
    ports:
      - "8001:8001"
    environment:
      DB_HOST: db_log
      DB_PORT: 3306
      DB_NAME: tp_log
      DB_USER: log_user
      DB_PASS: log_pass
    depends_on:
      - db_log

volumes:
    db_log_data: